goit:
  host: localhost
  port: 5432
  basename: postgres
  user: postgres
  password: password
spring:
  datasource:
    url: jdbc:postgresql://${goit.host}:${goit.port}/${goit.basename}
    username: ${goit.user}
    password: ${goit.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

myconfig:
  welcome:
    message: Hahaha user,
    img: hello.img
